vidium/urls.py
from django.urls import path
from . import views

app_name = 'vidium'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('upload/', views.Upload.upload, name='upload'),
    path('sort/<key>/<order>/', views.Index.sort, name='sort'),
]

workproduct/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vidium.urls'))
]

vidium/models.py
from django.db import models

# Create your models here.
class Gene(models.Model):
    chrom = models.CharField(max_length=200)
    pos = models.IntegerField()
    ref = models.CharField(max_length=10)
    alt = models.CharField(max_length=200)
    filter = models.CharField(max_length=200)
    af = models.FloatField()
    vf = models.FloatField()
    dp = models.IntegerField()
    allele = models.CharField(max_length=200)
    effect = models.CharField(max_length=200)
    impact = models.CharField(max_length=200)
    gene = models.CharField(max_length=200)

vidium/views.py
from django.shortcuts import render, redirect
from django.core import serializers
from django.views.generic import View
from django.contrib import messages
from django.http import HttpResponse

from xlrd import XLRDError
import pandas as pd
import pdb

from .models import Gene;
# Create your views here.

def getValues():
    genes = Gene.objects.all()
    values = genes.values_list('gene').distinct()
    values = map(lambda x: x[0], values)
    return values

def getResults(get_dict):
    genes = Gene.objects.all()
    for key, value in get_dict.items():
        value = value[0]
        if value:
            if key == "chromosome_start":
                genes = genes.filter(pos__gte=value)
            elif key == "chromosome_end":
                genes = genes.filter(pos__lte=value)
            elif key == "af_cutoff":
                genes = genes.filter(af__lte=float(value))
            elif key == 'chromosome_id':
                genes = genes.filter(chrom=value)
            elif key == 'gene':
                if value != ('Select the gene name'):
                    genes = genes.filter(gene=value)
    return genes

class Index(View):

    def get(self, request):
        """
        Method to display the information on dashboard
        """
        try: # Clear stored metadata of filters when on dashboard
            del request.session['filters']
        except KeyError:
            pass
        genes = Gene.objects.all()
        values = getValues() # Gets values to display in options
        return render(request, 'vidium/index.html', context = { 'genes' : genes, 'values': values })

    def post(self, request):
        """
        Processing request on search
        """
        genes = Gene.objects.all()
        get_dict = dict(request.POST) 
        flag = False
        if get_dict:
            start = get_dict['chromosome_start'][0]
            end = get_dict['chromosome_end'][0]
            af_cutoff = get_dict['af_cutoff'][0]
            if ((start and end) and (int(start) > int(end))): # Chromosome position validation check
                flag = True
                messages.warning(request, 'Chromosome start cannot be greater than chromosome end')
            if (af_cutoff and float(af_cutoff) > 1): # AF Cutoff validation
                flag = True
                messages.warning(request, 'AF Cutoff cannot be greater than 1')     
            request.session['filters'] = get_dict # Setting filters information for reference in sort       
        if not flag:
            genes = getResults(get_dict)
        values = getValues()
        return render(request, 'vidium/index.html', context = { 'genes' : genes, 'values': values })

    def sort(request, key, order):
        """
        Sorts based on the required key and order
        """
        filters = request.session.get('filters') # Getting filters if there are any set right now
        if filters:
            genes = getResults(filters)
        else:
            genes = Gene.objects.all()
        if (order == 'DESC'):
            key = '-' + key
            gene = genes.order_by(key.lower())
        else:
            gene = genes.order_by(key.lower())
        values = getValues() 
        return render(request, 'vidium/index.html', context = { 'genes' : gene, 'values': values})

class Upload(View):
    """
    Uploads file to populate table 
    """

    def process_file(datafile):
        """
        Takes the Excel file and processes it 
        """
        try:
            df = pd.read_excel(datafile, na_values=['None']) # For xlsx format
        except XLRDError:
            df = pd.read_csv(datafile) # For csv format
        df_dict = df.to_dict('index')
        for item in df_dict.items(): # Going through dict from file
            gene_dict = item[1]
            gene = Gene.objects.create(chrom=gene_dict['CHROM'], pos=gene_dict['POS'], ref=gene_dict['REF'], filter=gene_dict['FILTER'], alt=gene_dict['ALT'], af=gene_dict['AF'], vf=gene_dict['VF'], dp=gene_dict['DP'], allele=gene_dict['ALLELE'], effect=gene_dict['EFFECT'], impact=gene_dict['IMPACT'], gene=gene_dict['GENE']) # Adding entries in database
        gene_values = Gene.objects.values('gene').distinct()
        return gene_values
        
    def upload(request):
        if not request.FILES:
            messages.warning(request, 'Please select a file to upload!')
        else: 
            datafile = request.FILES['file'] # Getting file if uploaded
            values = Upload.process_file(datafile)
        return redirect('vidium:index')

vidium/templates/vidium/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <title>Vidium - Animal Health</title>
</head>
<body>
    <div class="container">
        {% block content %}{% endblock content %}
    </div>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
</body>
</html>

vidium/templates/vidium/index.html
{% extends 'vidium/base.html' %}

{% load static %}
{% block content %}
<div class="logo">
    <a href="{% url 'vidium:index' %}">
        <img src="{% static 'img/vidium_logo.png' %}" alt="Vidium logo">
    </a>
</div>

{% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible text-center fade show" role="alert">
        <strong>Warning!</strong> {{message}}
    </div>
    {% endfor %}
{% endif %}

<div class="p-4 justify-content-center card shadow mb-4">
    <div id="alert"></div>
    <form class="user" method="post" action="{% url 'vidium:index'%}">
        {% csrf_token %}
        <div class="row mb-3">
            <div class="col">
                <div class="form-group">
                    <label for="gene_name">Gene Name</label>
                    <select class="form-select" name="gene" id="gene_name">
                        <option selected>Select the gene name</option>
                        {% for name in values %}
                        <option value="{{ name }}">{{name}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="col">
                <label for="chromosome_id">Chromosome ID</label>
                <input name="chromosome_id" class="form-control" type="text" id="chromosome_id">
            </div>
            <div class="col">
                <label for="chromosome_start">Chromosome Start</label>
                <input name="chromosome_start" class="form-control" type="number" id="chromosome_start" onchange="validateChrom()" onkeyup="validateChrom()">
            </div>
        </div>
        <div class="row">
            <div class="col">
                <label for="chromosome_end">Chromosome End</label>
                <input name="chromosome_end" class="form-control" type="number" id="chromosome_end" onchange="validateChrom()" onkeyup="validateChrom()">
            </div>
            <div class="col">
                <label for="af_cutoff">AF Cutoff (<=)</label>
                <input name="af_cutoff" class="form-control" type="text" id="af_cutoff" onkeyup="validateAF()">
                <small id="af-note"></small>
            </div>
            <div class="col">
                <button class="btn btn-primary mt-4 px-4" type="submit"><i class="fas fa-search"></i> Search</button>
            </div>
        </div>
    </form>
</div>

{% include './partials/_table.html' %}

{% endblock content %}

vidium/templates/vidium/partials/_table.html
{% load static %}

<div class="card shadow p-4">
    <div class="card-head p-3">
        <div class="row">
            <div class="col-6">
                <h4>Genomic Data</h4>
            </div>
            <!-- <div class="col-6">
                <div class="form-group p-2">
                    <form action="{% url 'vidium:upload'%}" method="post" enctype="multipart/form-data" class="user text-center col-12">
                        <span class="mt-3">Upload file to populate table:</span>
                        {% csrf_token %}
                        <label id="uploadCsvLabel" for="uploadCsv" class="btn btn-primary">Choose File <i class="fas fa-file"></i></label>
                        <input id="uploadCsv" type="file" value="Browse" name="file" accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" hidden>
                        <button type="submit" formmethod="post" class="btn btn-outline-secondary" id="submitUpload">
                            Upload <i class="fas fa-upload"></i>
                        </button>
                    </form>
                </div>
            </div> -->
        </div> 
    </div>
    <div class="card-body">
        <table class="table table-bordered table-hover">
            <thead>
                <tr class="text-center"> 
                    <th scope="col">CHROM</th>
                    <th scope="col">POS</th>
                    <th scope="col">REF</th>
                    <th scope="col">ALT</th>
                    <th scope="col">FILTER</th>
                    <th scope="col">AF
                        <div>
                            <a href="/sort/AF/ASC"><small>ASC</small></a>
                            <a href="/sort/AF/DESC"><small>DESC</small></a>
                        </div>
                    </th>
                    <th scope="col">VF</th>
                    <th scope="col">DP</th>
                    <th scope="col">ALLELE</th>
                    <th scope="col">EFFECT</th>
                    <th scope="col">IMPACT</a>
                        <div>
                            <a href="/sort/IMPACT/ASC"><small>ASC</small></a>
                            <a href="/sort/IMPACT/DESC"><small>DESC</small></a>
                        </div>
                    </th>
                    <th scope="col">GENE</a>
                        <div>
                            <a href="/sort/GENE/ASC"><small>ASC</small></a>
                            <a href="/sort/GENE/DESC"><small>DESC</small></a>
                        </div>
                    </th>
                </tr>
            </thead>
            <tbody>
                {% for gene in genes %}
                    <tr class="text-center"> 
                        <td >{{gene.chrom}}</td>
                        <td>{{gene.pos}}</td>
                        <td>{{gene.ref}}</td>
                        <td>{{gene.alt}}</td>
                        <td>{{gene.filter}}</td>
                        <td>{{gene.af}}</td>
                        <td>{{gene.vf}}</td>
                        <td>{{gene.dp}}</td>
                        <td>{{gene.allele}}</td>
                        <td>{{gene.effect}}</td>
                        <td>{{gene.impact}}</td>
                        <td>{{gene.gene}}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>